# ETL Step 1 — Extract

Defines `extract(filepath)` — prints the CSV shape.

In [1]:
import pandas as pd

def extract(filepath, sample=None):
    if sample:
        df = pd.read_csv(filepath, nrows=sample, low_memory=False)
    else:
        chunks = []
        for chunk in pd.read_csv(filepath, chunksize=500_000, low_memory=False):
            chunks.append(chunk)
        df = pd.concat(chunks, ignore_index=True)

    pd.set_option('display.max_columns', None)
    print("Shape:", df.shape)
    print("\nColumns:", df.columns.tolist())
    print("\nDtypes:\n", df.dtypes)
    print("\nHead:")
    display(df.head(5))
    print("\nTail:")
    display(df.tail(5))
    print("\nMissing values:\n", df.isnull().sum())
    print("\nBasic stats:")
    display(df.describe())

    return df

## Run extract on Lightcast dataset

In [2]:
df = extract("../lightcast_job_postings.csv", sample=10000)

Shape: (10000, 131)

Columns: ['ID', 'LAST_UPDATED_DATE', 'LAST_UPDATED_TIMESTAMP', 'DUPLICATES', 'POSTED', 'EXPIRED', 'DURATION', 'SOURCE_TYPES', 'SOURCES', 'URL', 'ACTIVE_URLS', 'ACTIVE_SOURCES_INFO', 'TITLE_RAW', 'BODY', 'MODELED_EXPIRED', 'MODELED_DURATION', 'COMPANY', 'COMPANY_NAME', 'COMPANY_RAW', 'COMPANY_IS_STAFFING', 'EDUCATION_LEVELS', 'EDUCATION_LEVELS_NAME', 'MIN_EDULEVELS', 'MIN_EDULEVELS_NAME', 'MAX_EDULEVELS', 'MAX_EDULEVELS_NAME', 'EMPLOYMENT_TYPE', 'EMPLOYMENT_TYPE_NAME', 'MIN_YEARS_EXPERIENCE', 'MAX_YEARS_EXPERIENCE', 'IS_INTERNSHIP', 'SALARY', 'REMOTE_TYPE', 'REMOTE_TYPE_NAME', 'ORIGINAL_PAY_PERIOD', 'SALARY_TO', 'SALARY_FROM', 'LOCATION', 'CITY', 'CITY_NAME', 'COUNTY', 'COUNTY_NAME', 'MSA', 'MSA_NAME', 'STATE', 'STATE_NAME', 'COUNTY_OUTGOING', 'COUNTY_NAME_OUTGOING', 'COUNTY_INCOMING', 'COUNTY_NAME_INCOMING', 'MSA_OUTGOING', 'MSA_NAME_OUTGOING', 'MSA_INCOMING', 'MSA_NAME_INCOMING', 'NAICS2', 'NAICS2_NAME', 'NAICS3', 'NAICS3_NAME', 'NAICS4', 'NAICS4_NAME', 'NAICS5', 'NAICS5_NAME', 'NAICS6', 'NAICS6_NAME', 'TITLE', 'TITLE_NAME', 'TITLE_CLEAN', 'SKILLS', 'SKILLS_NAME', 'SPECIALIZED_SKILLS', 'SPECIALIZED_SKILLS_NAME', 'CERTIFICATIONS', 'CERTIFICATIONS_NAME', 'COMMON_SKILLS', 'COMMON_SKILLS_NAME', 'SOFTWARE_SKILLS', 'SOFTWARE_SKILLS_NAME', 'ONET', 'ONET_NAME', 'ONET_2019', 'ONET_2019_NAME', 'CIP6', 'CIP6_NAME', 'CIP4', 'CIP4_NAME', 'CIP2', 'CIP2_NAME', 'SOC_2021_2', 'SOC_2021_2_NAME', 'SOC_2021_3', 'SOC_2021_3_NAME', 'SOC_2021_4', 'SOC_2021_4_NAME', 'SOC_2021_5', 'SOC_2021_5_NAME', 'LOT_CAREER_AREA', 'LOT_CAREER_AREA_NAME', 'LOT_OCCUPATION', 'LOT_OCCUPATION_NAME', 'LOT_SPECIALIZED_OCCUPATION', 'LOT_SPECIALIZED_OCCUPATION_NAME', 'LOT_OCCUPATION_GROUP', 'LOT_OCCUPATION_GROUP_NAME', 'LOT_V6_SPECIALIZED_OCCUPATION', 'LOT_V6_SPECIALIZED_OCCUPATION_NAME', 'LOT_V6_OCCUPATION', 'LOT_V6_OCCUPATION_NAME', 'LOT_V6_OCCUPATION_GROUP', 'LOT_V6_OCCUPATION_GROUP_NAME', 'LOT_V6_CAREER_AREA', 'LOT_V6_CAREER_AREA_NAME', 'SOC_2', 'SOC_2_NAME', 'SOC_3', 'SOC_3_NAME', 'SOC_4', 'SOC_4_NAME', 'SOC_5', 'SOC_5_NAME', 'LIGHTCAST_SECTORS', 'LIGHTCAST_SECTORS_NAME', 'NAICS_2022_2', 'NAICS_2022_2_NAME', 'NAICS_2022_3', 'NAICS_2022_3_NAME', 'NAICS_2022_4', 'NAICS_2022_4_NAME', 'NAICS_2022_5', 'NAICS_2022_5_NAME', 'NAICS_2022_6', 'NAICS_2022_6_NAME']

Dtypes:
 ID                            str
LAST_UPDATED_DATE             str
LAST_UPDATED_TIMESTAMP        str
DUPLICATES                float64
POSTED                        str
                           ...
NAICS_2022_4_NAME             str
NAICS_2022_5              float64
NAICS_2022_5_NAME             str
NAICS_2022_6              float64
NAICS_2022_6_NAME             str
Length: 131, dtype: object

Head:

,ID,LAST_UPDATED_DATE,LAST_UPDATED_TIMESTAMP,DUPLICATES,POSTED,EXPIRED,DURATION,SOURCE_TYPES,SOURCES,URL,ACTIVE_URLS,ACTIVE_SOURCES_INFO,TITLE_RAW,BODY,MODELED_EXPIRED,MODELED_DURATION,COMPANY,COMPANY_NAME,COMPANY_RAW,COMPANY_IS_STAFFING,EDUCATION_LEVELS,EDUCATION_LEVELS_NAME,MIN_EDULEVELS,MIN_EDULEVELS_NAME,MAX_EDULEVELS,MAX_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,IS_INTERNSHIP,SALARY,REMOTE_TYPE,REMOTE_TYPE_NAME,ORIGINAL_PAY_PERIOD,SALARY_TO,SALARY_FROM,LOCATION,CITY,CITY_NAME,COUNTY,COUNTY_NAME,MSA,MSA_NAME,STATE,STATE_NAME,COUNTY_OUTGOING,COUNTY_NAME_OUTGOING,COUNTY_INCOMING,COUNTY_NAME_INCOMING,MSA_OUTGOING,MSA_NAME_OUTGOING,MSA_INCOMING,MSA_NAME_INCOMING,NAICS2,NAICS2_NAME,NAICS3,NAICS3_NAME,NAICS4,NAICS4_NAME,NAICS5,NAICS5_NAME,NAICS6,NAICS6_NAME,TITLE,TITLE_NAME,TITLE_CLEAN,SKILLS,SKILLS_NAME,SPECIALIZED_SKILLS,SPECIALIZED_SKILLS_NAME,CERTIFICATIONS,CERTIFICATIONS_NAME,COMMON_SKILLS,COMMON_SKILLS_NAME,SOFTWARE_SKILLS,SOFTWARE_SKILLS_NAME,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,CIP6,CIP6_NAME,CIP4,CIP4_NAME,CIP2,CIP2_NAME,SOC_2021_2,SOC_2021_2_NAME,SOC_2021_3,SOC_2021_3_NAME,SOC_2021_4,SOC_2021_4_NAME,SOC_2021_5,SOC_2021_5_NAME,LOT_CAREER_AREA,LOT_CAREER_AREA_NAME,LOT_OCCUPATION,LOT_OCCUPATION_NAME,LOT_SPECIALIZED_OCCUPATION,LOT_SPECIALIZED_OCCUPATION_NAME,LOT_OCCUPATION_GROUP,LOT_OCCUPATION_GROUP_NAME,LOT_V6_SPECIALIZED_OCCUPATION,LOT_V6_SPECIALIZED_OCCUPATION_NAME,LOT_V6_OCCUPATION,LOT_V6_OCCUPATION_NAME,LOT_V6_OCCUPATION_GROUP,LOT_V6_OCCUPATION_GROUP_NAME,LOT_V6_CAREER_AREA,LOT_V6_CAREER_AREA_NAME,SOC_2,SOC_2_NAME,SOC_3,SOC_3_NAME,SOC_4,SOC_4_NAME,SOC_5,SOC_5_NAME,LIGHTCAST_SECTORS,LIGHTCAST_SECTORS_NAME,NAICS_2022_2,NAICS_2022_2_NAME,NAICS_2022_3,NAICS_2022_3_NAME,NAICS_2022_4,NAICS_2022_4_NAME,NAICS_2022_5,NAICS_2022_5_NAME,NAICS_2022_6,NAICS_2022_6_NAME
0,1f57d95acf4dc67ed2819eb12f049f6a5c11782c,9/6/2024,2024-09-06 20:32:57.352 Z,0.0,6/2/2024,6/8/2024,6.0,"[\n ""Company""\n]","[\n ""brassring.com""\n]","[\n ""https://sjobs.brassring.com/TGnewUI/Sear...",[],NaN,Enterprise Analyst (II-III),31-May-2024\n\nEnterprise Analyst (II-III)\n\n...,6/8/2024,6.0,894731.0,Murphy USA,Murphy USA,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),2.0,2.0,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 33.20763,\n ""lon"": -92.6662674\n}",RWwgRG9yYWRvLCBBUg==,"El Dorado, AR",5139.0,"Union, AR",20980.0,"El Dorado, AR",5.0,Arkansas,5139.0,"Union, AR",5139.0,"Union, AR",20980.0,"El Dorado, AR",20980.0,"El Dorado, AR",44.0,Retail Trade,441.0,Motor Vehicle and Parts Dealers,4413.0,"Automotive Parts, Accessories, and Tire Retailers",44133.0,Automotive Parts and Accessories Retailers,441330.0,Automotive Parts and Accessories Retailers,ET29C073C03D1F86B4,Enterprise Analysts,enterprise analyst ii iii,"[\n ""KS126DB6T061MHD7RTGQ"",\n ""KS126706DPFD3...","[\n ""Merchandising"",\n ""Mathematics"",\n ""Pr...","[\n ""KS126DB6T061MHD7RTGQ"",\n ""KS128006L3V0H...","[\n ""Merchandising"",\n ""Predictive Modeling""...",[],[],"[\n ""KS126706DPFD3354M7YK"",\n ""KS1280B68GD79...","[\n ""Mathematics"",\n ""Presentations"",\n ""Re...","[\n ""KS440W865GC4VRBW6LJP"",\n ""KS13USA80NE38...","[\n ""SQL (Programming Language)"",\n ""Power B...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""45.0601"",\n ""27.0101""\n]","[\n ""Economics, General"",\n ""Mathematics, Ge...","[\n ""45.06"",\n ""27.01""\n]","[\n ""Economics"",\n ""Mathematics""\n]","[\n ""45"",\n ""27""\n]","[\n ""Social Sciences"",\n ""Mathematics and St...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101011.0,General ERP Analyst / Consultant,2310.0,Business Intelligence,23101011.0,General ERP Analyst / Consultant,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,[\n 7\n],"[\n ""Artificial Intelligence""\n]",44.0,Retail Trade,441.0,Motor Vehicle and Parts Dealers,4413.0,"Automotive Parts, Accessories, and Tire Retailers",44133.0,Automotive Parts and Accessories Retailers,441330.0,Automotive Parts and Accessories Retailers
1,0cb072af26757b6c4ea9464472a50a443af681ac,8/2/2024,2024-08-02 17:08:58.838 Z,0.0,6/2/2024,8/1/2024,NaN,"[\n ""Job Board""\n]","[\n ""maine.gov""\n]","[\n ""https://joblink.maine.gov/jobs/1085740""\n]",[],NaN,Oracle Consultant - Reports (3592),Oracle Consultant - Reports (3592)\n\nat SMX i...,8/1/2024,NaN,133098.0,Smx Corporation Limited,SMX,True,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),3.0,3.0,False,NaN,1.0,Remote,NaN,NaN,NaN,"{\n ""lat"": 44.3106241,\n ""lon"": -69.7794897\n}",QXVndXN0YSwgTUU=,"Augusta, ME",23011.0,"Kennebec, ME",12300.0,"Augusta-Waterville, ME",23.0,Maine,23011.0,"Kennebec, ME",23011.0,"Kennebec, ME",12300.0,"Augusta-Waterville, ME",12300.0,"Augusta-Waterville, ME",56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56132.0,Temporary Help Services,561320.0,Temporary Help Services,ET21DDA63780A7DC09,Oracle Consultants,oracle consultant reports,"[\n ""KS122626T550SLQ7QZ1C"",\n ""KS123YJ6KVWC9...","[\n ""Procurement"",\n ""Financial Statements"",...","[\n ""KS122626T550SLQ7QZ1C"",\n ""KS123YJ6KVWC9...","[\n ""Procurement"",\n ""Financial Statements"",...",[],[],[],[],"[\n ""BGSBF3F508F7F46312E3"",\n ""ESEA839CED378...","[\n ""Oracle Business Intelligence (BI) / OBIA...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101012.0,Oracle Consultant / Analyst,2310.0,Business Intelligence,23101012.0,Oracle Consultant / Analyst,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56132.0,Temporary Help Services,561320.0,Temporary Help Services
2,85318b12b3331fa490d32ad014379df01855c557,9/6/2024,2024-09-06 20:32:57.352 Z,1.0,6/2/2024,7/7/2024,35.0,"[\n ""Job Board""\n]","[\n ""dejobs.org""\n]","[\n ""https://dejobs.org/dallas-tx/data-analys...",[],NaN,Data Analyst,Taking care of people is at the heart of every...,6/10/2024,8.0,39063746.0,Sedgwick,Sedgwick,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),5.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 32.7766642,\n ""lon"": -96.7969879\n}",RGFsbGFzLCBUWA==,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",48.0,Texas,48113.0,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",52.0,Finance and Insurance,524.0,Insurance Carriers and Related Activities,5242.0,"Agencies, Brokerages, and Other Insurance Rela...",52429.0,Other Insurance Related Activities,524291.0,Claims Adjusting,ET3037E0C947A02404,Data Analysts,data analyst,"[\n ""KS1218W78FGVPVP2KXPX"",\n ""ESF3939CE1F80...","[\n ""Management"",\n ""Exception Reporting"",\n...","[\n ""ESF3939CE1F80C10C327"",\n ""KS120GV6C72JM...","[\n ""Exception Reporting"",\n ""Data Analysis""...","[\n ""KS683TN76T77DQDVBZ1B""\n]","[\n ""Security Clearance""\n]","[\n ""KS1218W78FGVPVP2KXPX"",\n ""BGS1ADAA36DB6...","[\n ""Management"",\n ""Report Writing"",\n ""In...","[\n ""KS126HY6YLTB9R7XJC4Z""\n]","[\n ""Microsoft Office""\n]",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,52.0,Finance and Insurance,524.0,Insurance Carriers and Related Activities,5242.0,"Agencies, Brokerages, and Other Insurance Rela...",52429.0,Other Insurance Related Activities,524291.0,Claims Adjusting
3,1b5c3941e54a1889ef4f8ae55b401a550708a310,9/6/2024,2024-09-06 20:32:57.352 Z,1.0,6/2/2024,7/20/2024,48.0,"[\n ""Job Board""\n]","[\n ""disabledperson.com"",\n ""dejobs.org""\n]","[\n ""https://www.disabledperson.com/jobs/5948...",[],NaN,Sr. Lead Data Mgmt. Analyst - SAS Product Owner,About this role:\n\nWells Fargo is looking for...,6/12/2024,10.0,37615159.0,Wells Fargo,Wells Fargo,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),3.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 33.4483771,\n ""lon"": -112.0740373\n}",UGhvZW5peCwgQVo=,"Phoenix, AZ",4013.0,"Maricopa, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",4.0,Arizona,4013.0,"Maricopa, AZ",4013.0,"Maricopa, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",52.0,Finance and Insurance,522.0,Credit Intermediation and Related Activities,5221.0,Depository Credit Intermediation,52211.0,Commercial Banking,522110.0,Commercial Banking,ET2114E0404BA30075,Management Analysts,sr lead data mgmt analyst sas product owner,"[\n ""KS123QX62QYTC4JF38H8"",\n ""KS7G6NP6R6L1H...","[\n ""Exit Strategies"",\n ""Reliability"",\n ""...","[\n ""KS123QX62QYTC4JF38H8"",\n ""KS441PQ64HT13...","[\n ""Exit Strategies"",\n ""User Story"",\n ""H...",[],[],"[\n ""KS7G6NP6R6L1H1SKFTSY"",\n ""KS1218W78FGVP...","[\n ""Reliability"",\n ""Management"",\n ""Strat...","[\n ""KS4409D76NW1S5LNCL18"",\n ""ESC7869CF7378...","[\n ""SAS (Software)"",\n ""Google Cloud Platfo...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,[\n 6\n],"[\n ""Data Privacy/Protection""\n]",52.0,Finance and Insurance,522.0,Credit Intermediation and Related Activities,5221.0,Depository Credit Intermediation,52211.0,Commercial Banking,522110.0,Commercial Banking
4,cb5ca25f02bdf25c13edfede7931508bfd9e858f,6/19/2024,2024-06-19 07:00:00.000 Z,0.0,6/2/2024,6/17/2024,15.0,"[\n ""FreeJobBoard""\n]","[\n ""craigslist.org""\n]","[\n ""https://modesto.craigslist.org/sls/77475...",[],NaN,Comisiones de $1000 - $3000 por semana... Comi...,Comisiones de $1000 - $3000 por semana... Comi...,6/17/2024,15.0,0.0,Unclassified,LH/GM,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,3.0,Part-time / full-time,NaN,NaN,False,92500.0,0.0,[None],year,150000.0,35000.0,"{\n ""lat"": 37.6392595,\n ""lon"": -120.9970014\n}",TW9kZXN0bywgQ0E=,"Modesto, CA",6099.0,"Stanislaus, CA",33700.0,"Modesto, CA",6.0,California,6099.0,"Stanislaus, CA",6099.0,"Stanislaus, CA",33700.0,"Modesto, CA",33700.0,"Modesto, CA",99.0,Unclassified Industry,999.0,Unclassified Industry,9999.0,Unclassified Industry,99999.0,Unclassified Industry,999999.0,Unclassified Industry,ET0000000000000000,Unclassified,comisiones de por semana comiensa rapido,[],[],[],[],[],[],[],[],[],[],15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101012.0,Oracle Consultant / Analyst,2310.0,Business Intelligence,23101012.0,Oracle Consultant / Analyst,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,99.0,Unclassified Industry,999.0,Unclassified Industry,9999.0,Unclassified Industry,99999.0,Unclassified Industry,999999.0,Unclassified Industry

Tail:

,ID,LAST_UPDATED_DATE,LAST_UPDATED_TIMESTAMP,DUPLICATES,POSTED,EXPIRED,DURATION,SOURCE_TYPES,SOURCES,URL,ACTIVE_URLS,ACTIVE_SOURCES_INFO,TITLE_RAW,BODY,MODELED_EXPIRED,MODELED_DURATION,COMPANY,COMPANY_NAME,COMPANY_RAW,COMPANY_IS_STAFFING,EDUCATION_LEVELS,EDUCATION_LEVELS_NAME,MIN_EDULEVELS,MIN_EDULEVELS_NAME,MAX_EDULEVELS,MAX_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,IS_INTERNSHIP,SALARY,REMOTE_TYPE,REMOTE_TYPE_NAME,ORIGINAL_PAY_PERIOD,SALARY_TO,SALARY_FROM,LOCATION,CITY,CITY_NAME,COUNTY,COUNTY_NAME,MSA,MSA_NAME,STATE,STATE_NAME,COUNTY_OUTGOING,COUNTY_NAME_OUTGOING,COUNTY_INCOMING,COUNTY_NAME_INCOMING,MSA_OUTGOING,MSA_NAME_OUTGOING,MSA_INCOMING,MSA_NAME_INCOMING,NAICS2,NAICS2_NAME,NAICS3,NAICS3_NAME,NAICS4,NAICS4_NAME,NAICS5,NAICS5_NAME,NAICS6,NAICS6_NAME,TITLE,TITLE_NAME,TITLE_CLEAN,SKILLS,SKILLS_NAME,SPECIALIZED_SKILLS,SPECIALIZED_SKILLS_NAME,CERTIFICATIONS,CERTIFICATIONS_NAME,COMMON_SKILLS,COMMON_SKILLS_NAME,SOFTWARE_SKILLS,SOFTWARE_SKILLS_NAME,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,CIP6,CIP6_NAME,CIP4,CIP4_NAME,CIP2,CIP2_NAME,SOC_2021_2,SOC_2021_2_NAME,SOC_2021_3,SOC_2021_3_NAME,SOC_2021_4,SOC_2021_4_NAME,SOC_2021_5,SOC_2021_5_NAME,LOT_CAREER_AREA,LOT_CAREER_AREA_NAME,LOT_OCCUPATION,LOT_OCCUPATION_NAME,LOT_SPECIALIZED_OCCUPATION,LOT_SPECIALIZED_OCCUPATION_NAME,LOT_OCCUPATION_GROUP,LOT_OCCUPATION_GROUP_NAME,LOT_V6_SPECIALIZED_OCCUPATION,LOT_V6_SPECIALIZED_OCCUPATION_NAME,LOT_V6_OCCUPATION,LOT_V6_OCCUPATION_NAME,LOT_V6_OCCUPATION_GROUP,LOT_V6_OCCUPATION_GROUP_NAME,LOT_V6_CAREER_AREA,LOT_V6_CAREER_AREA_NAME,SOC_2,SOC_2_NAME,SOC_3,SOC_3_NAME,SOC_4,SOC_4_NAME,SOC_5,SOC_5_NAME,LIGHTCAST_SECTORS,LIGHTCAST_SECTORS_NAME,NAICS_2022_2,NAICS_2022_2_NAME,NAICS_2022_3,NAICS_2022_3_NAME,NAICS_2022_4,NAICS_2022_4_NAME,NAICS_2022_5,NAICS_2022_5_NAME,NAICS_2022_6,NAICS_2022_6_NAME
9995,940d8426f7c612fa495a315a8dc1f1b75cfe78b3,10/9/2024,2024-10-09 16:54:50.883 Z,6.0,8/1/2024,10/4/2024,NaN,"[\n ""Job Board"",\n ""Recruiter"",\n ""Company""\n]","[\n ""fairygodboss.com"",\n ""spectrum.com"",\n ...","[\n ""https://www.indeed.com/viewjob?jk=5368b3...",[],NaN,"Principal Architect II, Spectrum Enterprise","Principal Architect II, Spectrum Enterprise Sp...",8/12/2024,11.0,41110818.0,Spectrum,Spectrum,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),10.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 30.267153,\n ""lon"": -97.7430608\n}",QXVzdGluLCBUWA==,"Austin, TX",48453.0,"Travis, TX",12420.0,"Austin-Round Rock-Georgetown, TX",48.0,Texas,48453.0,"Travis, TX",48453.0,"Travis, TX",12420.0,"Austin-Round Rock-Georgetown, TX",12420.0,"Austin-Round Rock-San Marcos, TX",51.0,Information,517.0,Telecommunications,5171.0,Wired and Wireless Telecommunications (except ...,51712.0,Telecommunications Resellers and Agents for Wi...,517121.0,Telecommunications Resellers,ET7767EEDBF263F7B7,Principal Architects,principal architect ii enterprise,"[\n ""KS1218W78FGVPVP2KXPX"",\n ""KS7G747655VG2...","[\n ""Management"",\n ""Prioritization"",\n ""Ar...","[\n ""KS120MG72SY2QP2VH1YL"",\n ""KS120XP636CB5...","[\n ""Architectural Development"",\n ""Telecomm...",[],[],"[\n ""KS1218W78FGVPVP2KXPX"",\n ""KS7G747655VG2...","[\n ""Management"",\n ""Prioritization"",\n ""Co...",[],[],15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""11.0701"",\n ""23.0101""\n]","[\n ""Computer Science"",\n ""English Language ...","[\n ""11.07"",\n ""23.01""\n]","[\n ""Computer Science"",\n ""English Language ...","[\n ""11"",\n ""23""\n]","[\n ""Computer and Information Sciences and Su...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231510.0,Computer Systems Engineer / Architect,23151012.0,Enterprise Architect,2315.0,Network and Systems Engineering,23151012.0,Enterprise Architect,231510.0,Computer Systems Engineer / Architect,2315.0,Network and Systems Engineering,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,51.0,Information,517.0,Telecommunications,5171.0,Wired and Wireless Telecommunications (except ...,51712.0,Telecommunications Resellers and Agents for Wi...,517121.0,Telecommunications Resellers
9996,e6e043de5ae4b6de205d964580dd53b3fcc39591,10/9/2024,2024-10-09 18:07:44.758 Z,0.0,8/1/2024,9/30/2024,NaN,"[\n ""Job Board""\n]","[\n ""dice.com""\n]","[\n ""https://www.dice.com/job-detail/26515920...",[],NaN,SAP PP S4 Hana,"SAP PP S4 Hana\nLocation- Chicago, IL-Onsite D...",NaN,NaN,38135380.0,KAnand,K Anand Corporation,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),NaN,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 41.8781136,\n ""lon"": -87.6297982\n}",Q2hpY2FnbywgSUw=,"Chicago, IL",17031.0,"Cook, IL",16980.0,"Chicago-Naperville-Elgin, IL-IN-WI",17.0,Illinois,17031.0,"Cook, IL",17031.0,"Cook, IL",16980.0,"Chicago-Naperville-Elgin, IL-IN-WI",16980.0,"Chicago-Naperville-Elgin, IL-IN",54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541511.0,Custom Computer Programming Services,ET0000000000000000,Unclassified,sap pp s hana,"[\n ""KS44086772RVPJQ1SVW6"",\n ""KS4409070WHN6...","[\n ""SAP Applications"",\n ""SAP Production Pl...","[\n ""KS44086772RVPJQ1SVW6"",\n ""KS4409070WHN6...","[\n ""SAP Applications"",\n ""SAP Production Pl...",[],[],[],[],"[\n ""KS44086772RVPJQ1SVW6"",\n ""KS4409070WHN6...","[\n ""SAP Applications"",\n ""SAP Production Pl...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101013.0,SAP Analyst / Admin,2310.0,Business Intelligence,23101013.0,SAP Analyst / Admin,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541511.0,Custom Computer Programming Services
9997,c10c43822f16d86a41225c4658687cdb7d8e7d08,10/9/2024,2024-10-09 18:07:44.758 Z,0.0,8/1/2024,8/7/2024,6.0,"[\n ""Job Board""\n]","[\n ""dice.com""\n]","[\n ""https://www.dice.com/job-detail/1712acf3...",[],NaN,Data Analyst,Data Analyst\nPosition: Data Analyst/ Data Sci...,8/7/2024,6.0,35590786.0,Pinnacle Group,Pinnacle Group,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),NaN,NaN,False,115440.0,0.0,[None],hour,120640.0,110240.0,"{\n ""lat"": 40.6022939,\n ""lon"": -75.4714098\n}",QWxsZW50b3duLCBQQQ==,"Allentown, PA",42077.0,"Lehigh, PA",10900.0,"Allentown-Bethlehem-Easton, PA-NJ",42.0,Pennsylvania,42077.0,"Lehigh, PA",42077.0,"Lehigh, PA",10900.0,"Allentown-Bethlehem-Easton, PA-NJ",10900.0,"Allentown-Bethlehem-Easton, PA-NJ",52.0,Finance and Insurance,524.0,Insurance Carriers and Related Activities,5242.0,"Agencies, Brokerages, and Other Insurance Rela...",52421.0,Insurance Agencies and Brokerages,524210.0,Insurance Agencies and Brokerages,ET3037E0C947A02404,Data Analysts,data analyst,"[\n ""KS1219977HCLGR8H96W8"",\n ""KS7LO8P3MXB93...","[\n ""Business Support Systems"",\n ""Data Scie...","[\n ""KS1219977HCLGR8H96W8"",\n ""KS7LO8P3MXB93...","[\n ""Business Support Systems"",\n ""Data Scie...",[],[],"[\n ""KS122556LMQ829GZCCRV""\n]","[\n ""Communication""\n]","[\n ""KS125LS6N7WP4S6SFTCK"",\n ""KS1218L60PDVZ...","[\n ""Python (Programming Language)"",\n ""Dash...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""30.7001"",\n ""11.0701""\n]","[\n ""Data Science, General"",\n ""Computer Sci...","[\n ""30.70"",\n ""11.07""\n]","[\n ""Data Science"",\n ""Computer Science""\n]","[\n ""30"",\n ""11""\n]","[\n ""Multi/Interdisciplinary Studies"",\n ""Co...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,52.0,Finance and Insurance,524.0,Insurance Carriers and Related Activities,5242.0,"Agencies, Brokerages, and Other Insurance Rela...",52421.0,Insurance Agencies and Brokerages,524210.0,Insurance Agencies and Brokerages
9998,d9a4088e5f8621e10426a2566702db664674a728,10/22/2024,2024-10-22 13:49:03.059 Z,1.0,8/1/2024,10/21/2024,NaN,"[\n ""Company"",\n ""Job Board""\n]","[\n ""disabledperson.com""\n]","[\n ""https://www.disabledperson.com/jobs/6142...",[],NaN,Sr. Oracle EPM Consultant,Sr. Oracle EPM Consultant at Beacon Hill Staff...,9/5/2024,35.0,43148341.0,Beacon Hill Staffing Group,"Beacon Hill Staffing Group, LLC",True,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),7.0,NaN,False,175000.0,1.0,Remote,year,175000.0,175000.0,"{\n ""lat"": 30.4514677,\n ""lon"": -91.1871466\n}",QmF0b24gUm91Z2UsIExB,"Baton Rouge, LA",22033.0,"East Baton Rouge, LA",12940.0,"Baton Rouge, LA",22.0,Louisiana,22033.0,"East Baton Rouge, LA",22033.0,"East Baton Rouge, LA",12940.0,"Baton Rouge, LA",12940.0,"Baton Rouge, LA",56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56131.0,Employment Placement Agencies and Executive Se...,561311.0,Employment Placement Agencies,ETC79EBC6A5480AAF6,EPM Consultants,sr oracle epm consultant,"[\n ""ESC91AF2C3175C6D924C"",\n ""KSRGLA2SD4T20...","[\n ""Oracle Cloud"",\n ""On Prem"",\n ""Busines...","[\n ""ESC91AF2C3175C6D924C"",\n ""KSRGLA2SD4T20...","[\n ""Oracle Cloud"",\n ""On Prem"",\n ""Busines...",[],[],"[\n ""KS1200H6XYN1CR0G5NZ0"",\n ""ES70CD6E89F6D...","[\n ""Microsoft Excel"",\n ""Relationship Manag...","[\n ""ESC91AF2C3175C6D924C"",\n ""KS124PM66CYVH...","[\n ""Oracle Cloud"",\n ""Oracle Hyperion Finan...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101012.0,Oracle Consultant / Analyst,2310.0,Business Intelligence,23101012.0,Oracle Consultant / Analyst,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56131.0,Employment Placement Agencies and Executive Se...,561311.0,Employment Placement Agencies
9999,aa9d6161a233e2ac0cdd0360ceeb33ee2b355d2c,10/9/2024,2024-10-09 18:07:44.758 Z,0.0,8/1/2024,9/30/2024,NaN,"[\n ""Job Board""\n]","[\n ""dice.com""\n]","[\n ""https://www.dice.com/job-detail/6ce4db61...",[],NaN,SAP SD,SAP SD\nPosition: SAP SD consultant\nLocation:...,8/20/2024,19.0,44882672.0,Della Infotech,Della Infotech,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),5.0,5.0,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 37.36883,\n ""lon"": -122.0363496\n}",U3Vubnl2YWxlLCBDQQ==,"Sunnyvale, CA",6085.0,"Santa Clara, CA",41940.0,"San Jose-Sunnyvale-Santa Clara, CA",6.0,California,6085.0,"Santa Clara, CA",6085.0,"Santa Clara, CA",41940.0,"San Jose-Sunnyvale-Santa Clara, CA",41940.0,"San Jose-Sunnyvale-Santa Clara, CA",54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541512.0,Computer Systems Design Services,ET0000000000000000,Unclassified,sap sd,"[\n ""BGSD348B3C19CF65E8D1"",\n ""KS121Z26S4VJL...","[\n ""Cross-Functional Integration"",\n ""Custo...","[\n ""BGSD348B3C19CF65E8D1"",\n ""BGSACC7757544...","[\n ""Cross-Functional Integration"",\n ""Order...",[],[],"[\n ""KS121Z26S4VJLQ1WXN21"",\n ""KS123X777H5WF...","[\n ""Customer Service"",\n ""Sales""\n]","[\n ""KS127FD68FN8LGGXD378"",\n ""KS440946GQJT6...","[\n ""Order Management Systems"",\n ""SAP Sales...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101013.0,SAP Analyst / Admin,2310.0,Business Intelligence,23101013.0,SAP Analyst / Admin,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541512.0,Computer Systems Design Services

Missing values:
 ID                         6
LAST_UPDATED_DATE          6
LAST_UPDATED_TIMESTAMP     6
DUPLICATES                 6
POSTED                     6
                          ..
NAICS_2022_4_NAME         12
NAICS_2022_5              12
NAICS_2022_5_NAME         12
NAICS_2022_6              12
NAICS_2022_6_NAME         12
Length: 131, dtype: int64

Basic stats:

,DUPLICATES,DURATION,MODELED_DURATION,COMPANY,MIN_EDULEVELS,MAX_EDULEVELS,EMPLOYMENT_TYPE,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,SALARY,REMOTE_TYPE,SALARY_TO,SALARY_FROM,COUNTY,MSA,STATE,COUNTY_OUTGOING,COUNTY_INCOMING,MSA_OUTGOING,MSA_INCOMING,NAICS2,NAICS3,NAICS4,NAICS5,NAICS6,LOT_CAREER_AREA,LOT_OCCUPATION,LOT_SPECIALIZED_OCCUPATION,LOT_OCCUPATION_GROUP,LOT_V6_SPECIALIZED_OCCUPATION,LOT_V6_OCCUPATION,LOT_V6_OCCUPATION_GROUP,LOT_V6_CAREER_AREA,NAICS_2022_2,NAICS_2022_3,NAICS_2022_4,NAICS_2022_5,NAICS_2022_6
count,9994.000000,6367.000000,7286.000000,9.988000e+03,9988.000000,2258.000000,9988.000000,6794.000000,1145.000000,4252.000000,9988.000000,4464.000000,4464.000000,9988.000000,9484.000000,9988.000000,9988.000000,9988.000000,9484.000000,9484.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9.988000e+03,9988.000000,9.988000e+03,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000,9988.000000
mean,1.084050,22.297785,19.494373,3.697865e+07,31.826292,2.829495,1.061674,5.441860,3.737118,117716.049389,0.290549,135862.517249,93781.577733,28691.547056,29686.888444,28.558470,28691.547056,28693.601622,29686.888444,29700.112822,58.179215,586.115939,5865.699239,58660.077593,586603.259011,22.272527,223844.588807,2.238447e+07,2238.333600,2.238447e+07,223844.588807,2238.333600,22.272527,58.179215,586.115939,5865.699239,58660.077593,586603.259011
std,2.906003,14.379377,12.967799,3.027306e+07,44.900999,0.582326,0.295151,3.274604,2.520523,44977.990637,0.651486,59630.242664,40308.163668,16181.738485,11559.337079,16.147249,16181.738485,16181.442875,11559.337079,11559.180923,18.467146,184.651734,1847.962098,18481.639631,184818.388185,2.872690,28725.687641,2.872569e+06,287.253734,2.872569e+06,28725.687641,287.253734,2.872690,18.467146,184.651734,1847.962098,18481.639631,184818.388185
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000,1.000000,0.000000,0.000000,24544.000000,0.000000,12480.000000,11015.000000,1003.000000,10100.000000,1.000000,1003.000000,1003.000000,10100.000000,10100.000000,11.000000,111.000000,1111.000000,11119.000000,111199.000000,11.000000,111110.000000,1.111101e+07,1111.000000,1.111101e+07,111110.000000,1111.000000,11.000000,11.000000,111.000000,1111.000000,11119.000000,111199.000000
25%,0.000000,11.000000,10.000000,6.076858e+06,2.000000,3.000000,1.000000,3.000000,2.000000,84500.000000,0.000000,91448.750000,64126.000000,13067.000000,18140.000000,13.000000,13067.000000,13067.000000,18140.000000,18180.000000,52.000000,522.000000,5222.000000,52229.000000,522299.000000,23.000000,231010.000000,2.310101e+07,2310.000000,2.310101e+07,231010.000000,2310.000000,23.000000,52.000000,522.000000,5222.000000,52229.000000,522299.000000
50%,0.000000,18.000000,16.000000,3.761516e+07,2.000000,3.000000,1.000000,5.000000,3.000000,115653.500000,0.000000,131900.000000,88600.000000,29095.000000,31080.000000,29.000000,29095.000000,29095.000000,31080.000000,31080.000000,54.000000,541.000000,5415.000000,54151.000000,541519.000000,23.000000,231113.000000,2.311131e+07,2311.000000,2.311131e+07,231113.000000,2311.000000,23.000000,54.000000,541.000000,5415.000000,54151.000000,541519.000000
75%,1.000000,32.000000,27.000000,4.360568e+07,99.000000,3.000000,1.000000,7.000000,5.000000,147500.000000,0.000000,176800.000000,117300.000000,42999.000000,39580.000000,42.000000,42999.000000,42999.000000,39580.000000,39580.000000,56.000000,561.000000,5613.250000,56135.000000,561350.000000,23.000000,231113.000000,2.311131e+07,2311.000000,2.311131e+07,231113.000000,2311.000000,23.000000,56.000000,561.000000,5613.250000,56135.000000,561350.000000
max,100.000000,59.000000,59.000000,1.082365e+08,99.000000,4.000000,3.000000,15.000000,12.000000,500000.000000,3.000000,500000.000000,500000.000000,56999.000000,49660.000000,56.000000,56999.000000,56999.000000,49660.000000,49660.000000,99.000000,999.000000,9999.000000,99999.000000,999999.000000,27.000000,271211.000000,2.712111e+07,2712.000000,2.712111e+07,271211.000000,2712.000000,27.000000,99.000000,999.000000,9999.000000,99999.000000,999999.000000

In [3]:
df.columns[26:53].tolist()

['EMPLOYMENT_TYPE',
 'EMPLOYMENT_TYPE_NAME',
 'MIN_YEARS_EXPERIENCE',
 'MAX_YEARS_EXPERIENCE',
 'IS_INTERNSHIP',
 'SALARY',
 'REMOTE_TYPE',
 'REMOTE_TYPE_NAME',
 'ORIGINAL_PAY_PERIOD',
 'SALARY_TO',
 'SALARY_FROM',
 'LOCATION',
 'CITY',
 'CITY_NAME',
 'COUNTY',
 'COUNTY_NAME',
 'MSA',
 'MSA_NAME',
 'STATE',
 'STATE_NAME',
 'COUNTY_OUTGOING',
 'COUNTY_NAME_OUTGOING',
 'COUNTY_INCOMING',
 'COUNTY_NAME_INCOMING',
 'MSA_OUTGOING',
 'MSA_NAME_OUTGOING',
 'MSA_INCOMING']

In [4]:
pd.set_option('display.max_columns', None)
df.iloc[:, 26:53].head()

,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,IS_INTERNSHIP,SALARY,REMOTE_TYPE,REMOTE_TYPE_NAME,ORIGINAL_PAY_PERIOD,SALARY_TO,SALARY_FROM,LOCATION,CITY,CITY_NAME,COUNTY,COUNTY_NAME,MSA,MSA_NAME,STATE,STATE_NAME,COUNTY_OUTGOING,COUNTY_NAME_OUTGOING,COUNTY_INCOMING,COUNTY_NAME_INCOMING,MSA_OUTGOING,MSA_NAME_OUTGOING,MSA_INCOMING
0,1.0,Full-time (> 32 hours),2.0,2.0,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 33.20763,\n ""lon"": -92.6662674\n}",RWwgRG9yYWRvLCBBUg==,"El Dorado, AR",5139.0,"Union, AR",20980.0,"El Dorado, AR",5.0,Arkansas,5139.0,"Union, AR",5139.0,"Union, AR",20980.0,"El Dorado, AR",20980.0
1,1.0,Full-time (> 32 hours),3.0,3.0,False,NaN,1.0,Remote,NaN,NaN,NaN,"{\n ""lat"": 44.3106241,\n ""lon"": -69.7794897\n}",QXVndXN0YSwgTUU=,"Augusta, ME",23011.0,"Kennebec, ME",12300.0,"Augusta-Waterville, ME",23.0,Maine,23011.0,"Kennebec, ME",23011.0,"Kennebec, ME",12300.0,"Augusta-Waterville, ME",12300.0
2,1.0,Full-time (> 32 hours),5.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 32.7766642,\n ""lon"": -96.7969879\n}",RGFsbGFzLCBUWA==,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",48.0,Texas,48113.0,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",19100.0
3,1.0,Full-time (> 32 hours),3.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 33.4483771,\n ""lon"": -112.0740373\n}",UGhvZW5peCwgQVo=,"Phoenix, AZ",4013.0,"Maricopa, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",4.0,Arizona,4013.0,"Maricopa, AZ",4013.0,"Maricopa, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",38060.0
4,3.0,Part-time / full-time,NaN,NaN,False,92500.0,0.0,[None],year,150000.0,35000.0,"{\n ""lat"": 37.6392595,\n ""lon"": -120.9970014\n}",TW9kZXN0bywgQ0E=,"Modesto, CA",6099.0,"Stanislaus, CA",33700.0,"Modesto, CA",6.0,California,6099.0,"Stanislaus, CA",6099.0,"Stanislaus, CA",33700.0,"Modesto, CA",33700.0